[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run deploy"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "vouchy-discord-bot"

[services.volumes]
data = "/app/data" 