[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "vouchy-discord-bot"

[services.volumes]
data = "/app/data" 